---
name: Test Custom Action with Inputs

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
      tags:
        description: "Test scenario tags"
        required: false
        default: "none"
  push:
    branches:
      - "testing"  # Ensure branch name is correct

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use latest version

      - name: Print input values
        run: |
          echo "Log Level: ${{ github.event.inputs.logLevel }}"
          echo "Tags: ${{ github.event.inputs.tags }}"
