name: Dispatcher Workflow

on:
  workflow_dispatch:
    inputs:
      choice:
        description: 'Choose Workflow (A or B)'
        required: true
        type: choice
        options:
          - A
          - B

jobs:
  trigger-workflow-A:
    if: ${{ github.event.inputs.choice == 'A' }}
    uses: ./.github/workflows/workflow-a.yml

  trigger-workflow-B:
    if: ${{ github.event.inputs.choice == 'B' }}
    uses: ./.github/workflows/workflow-b.yml
