name: Test Custom Action with Inputs
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning

jobs:
  taking-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print input values
        run: |
          echo "Log Level: ${{ github.event.inputs.logLevel }}"

  deploy-via-A:
    needs: taking-inputs
    runs-on: ubuntu-latest
    if: github.event.inputs.logLevel == 'A'
    steps:
      - name: Print A
        run: echo "Deploying via A"

  deploy-via-B:
    needs: taking-inputs
    runs-on: ubuntu-latest
    if: github.event.inputs.logLevel == 'B'
    steps:
      - name: Print B
        run: echo "Deploying via B"
