name: Test Custom Action with Inputs
on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        required: true
        default: warning

jobs:
  print-inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print input values
        run: |
          echo "Log Level: ${{ github.event.inputs.logLevel }}"

      - name: Conditional Print Based on Input
        run: |
          if [[ "${{ github.event.inputs.logLevel }}" == "A" ]]; then
            echo "Input is A"
          elif [[ "${{ github.event.inputs.logLevel }}" == "B" ]]; then
            echo "Input is B"
          else
            echo "Input is neither A nor B"
          fi
